"use strict";

(function () {



/**
 * TODO:
 * Write some JavaScript that uses a `confirm` dialog to ask the user if they
 * would like to enter a number. If they click 'Ok', prompt the user for a
 * number, then use 3 separate alerts to tell the user:
 *
 * - whether the number is even or odd
 * - what the number plus 100 is
 * - if the number is negative or positive
 *
 * if what the user enters is not a number, use an alert to tell them that, and
 * do *not* display any of the above information.
 *
 * Can you refactor your code to use functions?
 */



//creating a new function to catch the number coming from prompting the users ... need to be applied ...

    function giveMeaNumber(message) {

        var input=prompt(message);
        var numero=parseInt(input);

        return numero;


    }


    var likes=confirm("would you like to type a number?");


    function isOdd(numero) {
        var odd= (numero%2)!=(0);
        return odd;

    }


    function positive(numero) {

        var positivo=(numero>=0);

        return positivo;
    }
 function primera(likes) {

 }
    if(likes) {


        var numero =(prompt("please type the number you want"));
        if (!(isNaN(numero))) {
            if (isOdd(numero)) {
                alert("your number is Odd");
            }
            else {
                alert("your number is even");
            }
            alert("your number plus 100 is: "+ (Number(numero)+100));

            if( positive(numero)){
                alert("your number is positive")
            }
            else {
                alert("you number is negative");
            }
        }
        else {

            return alert("the data you typed in is not a number, sorry");
        }
    }


/* ########################################################################## */

/**
 * TODO:
 * Create a function named `analyzeColor` that accepts a string that is a color
 * name as input. This function should return a message that related to that
 * color. Only worry about the colors defined above, if the color passed is not
 * one of the ones defined above, return a message that says so
 *
 * Example:
 *  > analyzeColor('blue') // returns "blue is the color of the sky"
 *  > analyzeColor('red') // returns "Strawberries are red"
 *  > analyzeColor('cyan') // returns "I don't know anything about cyan"
 *
 * You should use an if-else-if-else block to return different messages.
 *
 * Test your function by passing various string literals to it and
 * console.logging the function's return value
 */





    var colormine=prompt("please enter a color");
    colormine=colormine.toLocaleLowerCase();



   function analyzeColor(color) {


       if (color == "blue") {

           alert("blue is the color of the sky");

       }

       else if (color == "red") {

           alert("red is the color of blood");
       }


       else if (color == "green") {

           alert("green is the color of weed");

       }


       else if (color == "yellow") {

           alert("yellow is the color of the sun");
       }
       else if (color=="orange")
       {
           alert("orange is a not great color")
       }

       else if (color=="indigo")
       {
           alert("indigo is a not conventional color")
       }
       else if (color=="violet")
       {
           alert("roses are red , violets are blue")
       }

       else {
           alert("please pick another color");
       }


   }

   analyzeColor(colormine);




// Don't change the next two lines!
// These lines create two variables for you:
// - `colors`: a list of the colors of the rainbow
// - `randomColor`: contains a single random color value from the list (this
//                  will contain a different color everytime the page loads)
var colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'];
var randomColor = colors[Math.floor(Math.random() * colors.length)];
/**
 * TODO:
 * Pass the `randomColor` variable to your function and console.log the results.
 * You should see a different message everytime you refresh the page
 */

alert("this will be generated by the Random color value");

alert(analyzeColor(randomColor));


/**
 * TODO:
 * Refactor your above function to use a switch-case statement
 */

function analyzeColorsw(color) {


    switch (color){

        case "blue":

            alert("blue is the color of the sky");
            break;



        case "red":

            alert("red is the color of blood");
            break



        case "green":

            alert("green is the color of weed");
            break


        case "yellow":

            alert("yellow is the color of the sun");
            break

        case "orange":

            alert("orange is a not great color")
            break;


        case "indigo":

            alert("indigo is a not conventional color")
            break;

        case "violet":

            alert("roses are red , violets are blue")
            break;



         default:
             alert("please pick another color");
             break;
    }


}



alert("this will be done using swich");
var givemeacolor=prompt("please type a color");

analyzeColorsw(givemeacolor);


/**
 * TODO:
 * Prompt the user for a color when the page loads, and pass the input from the
 * user to your `analyzeColor` function. Alert the return value from your
 * function to show it to the user.
 */

/* ########################################################################## */

/**
 * TODO:
 * Suppose there's a promotion in Walmart, each customer is given a randomly
 * generated "lucky number" between 0 and 5. If your lucky number is 0 you have
 * no discount, if your lucky number is 1 you'll get a 10% discount, if it's 2,
 * the discount is 25%, if it's 3, 35%, if it's 4, 50%, and if it's 5 you'll get
 * all for free!.
 *
 * Write a function named `calculateTotal` that accepts a lucky number and total
 * amount, and returns the discounted price.
 *
 * Example:
 * calculateTotal(0, 100) // returns 100
 * calculateTotal(4, 100) // returns 50
 * calculateTotal(5, 100) // returns 0
 *
 * Test your function by passing it various values and checking for the expected
 * return value.
 */

function discount(originalprice,discountpercent) {

    return (originalprice-(originalprice*discountpercent));

}

function promotion(luckyNumber, totalPrice) {

    var totalTopay;

    switch (luckyNumber){
        case "0":
            totalTopay =parseFloat(discount(totalPrice,1));
            break;

        case "1":
            totalTopay=parseFloat(discount(totalPrice,0.10));
            break;

        case "2":
            totalTopay=parseFloat(discount(totalPrice,0.25));
            break;

        case "3":
            totalTopay=parseFloat(discount(totalPrice,0.35));
            break;
        case "4":
            totalTopay=parseFloat(discount(totalPrice,0.50));
            break;
        case "5":
            totalTopay=parseFloat(discount(totalPrice,0));
            break;
        default:
            totalTopay=totalPrice;
            alert("You didn't enter any lucky number");
            break;

    }

    return totalTopay;

}


var numero1=prompt("please enter your total price for Walmart today");
var numero2=prompt("please enter your lucky number");

alert("you total amount to pay with discount is "+ promotion(numero2,numero1));







/**
 * TODO:
 * Uncomment the line below to generate a random number between 0 and 6.
 * Prompt the user for their total bill, then use your `calculateTotal` function
 * and alerts to display to the user what their lucky number was, what their
 * price before the discount was, and what their price after the discount is.
 */


//Generate a random number between 0 and 6
var luckyNumber = Math.floor(Math.random() * 6);

var spends=prompt("please enter your total amount to pay, your lucky number will be generated automatically");

alert("your total amount to pay is"+ promotion(luckyNumber,spends));


})();